config/routes.rb
ChicagoYelpInspection::Application.routes.draw do
  root "reviews#search"

  resources :inspections
  resources :businesses

  get "/reviews/search" => "reviews#search"
  get "/reviews/results" => "reviews#search"
  post "/reviews/results" => "reviews#results"
  get "/reviews/howto" => "reviews#howto"

end

app/controllers/businesses_controller.rb
require 'json'
require 'yelp'

class BusinessesController < ApplicationController
  before_action :set_business, only: [:show]

  # GET /businesses
  # GET /businesses.json

  def index
    @businesses = Business.all
  end

  def search
  end

  # def results
  #   @location = params[:location]

  #   parameters = { term: "food", limit: 10 }
  #   response = Yelp.client.search(@location, parameters) 
  #   @responses = response.businesses 
  #   @results = []  

  #   @responses.each do |yelp_business|
  #     business_id = URI.escape(yelp_business.id)
  #     business = Yelp.client.business(business_id)
  #     inspection_info = search_inspections(business)
  #     business_info = [business.name, business.rating_img_url, inspection_info, business.url]
  #     @results.push(business_info)
  #   end
  # end  

  # def search_inspections(business) 
  #   address = business.location.address[0].to_s.upcase
  #   business_found = Address.find_by("address LIKE ?", "%#{address}%")

  #   if business_found.nil?
  #     return [["", "no inspections found"]]
  #   end

  #   inspections = Inspection.where(:business_id => business_found.business_id).order(inspect_date: :desc)
  #   @inspect_results = []

  #   inspections.each do |inspection|
  #     if (inspection.results.include?("Pass") || inspection.results.include?("Fail"))
  #       inspection_data = [inspection.inspect_date, inspection.results, inspection.violations, inspection.id]
  #       @inspect_results.push(inspection_data)
  #     end
  #   end

  #   return @inspect_results

  # end

  # GET /businesses/1
  # GET /businesses/1.json
  def show
  end

  # GET /businesses/new
  def new
    @business = Business.new
  end

  # GET /businesses/1/edit
  def edit
  end

  # POST /businesses
  # POST /businesses.json
  def create
    @business = Business.new(business_params)

    respond_to do |format|
      if @business.save
        format.html { redirect_to @business, notice: 'Business was successfully created.' }
        format.json { render action: 'show', status: :created, location: @business }
      else
        format.html { render action: 'new' }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /businesses/1
  # PATCH/PUT /businesses/1.json
  def update
    respond_to do |format|
      if @business.update(business_params)
        format.html { redirect_to @business, notice: 'Business was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /businesses/1
  # DELETE /businesses/1.json
  def destroy
    @business.destroy
    respond_to do |format|
      format.html { redirect_to businesses_url }
      format.json { head :no_content }
    end
  end

  private
    #Use callbacks to share common setup or constraints between actions.
    def set_business
      @business = Business.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def business_params
      params.permit(:dba_name, :aka_name, :license, :facility_type, :address, :zip, :latitude, :longitude, :location)
    end
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/views/businesses/_form.html.erb
<%= form_for(@business) do |f| %>
  <% if @business.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@business.errors.count, "error") %> prohibited this business from being saved:</h2>

      <ul>
      <% @business.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :dba_name %><br>
    <%= f.text_field :dba_name %>
  </div>
  <div class="field">
    <%= f.label :aka_name %><br>
    <%= f.text_field :aka_name %>
  </div>
  <div class="field">
    <%= f.label :license %><br>
    <%= f.number_field :license %>
  </div>
  <div class="field">
    <%= f.label :facility_type %><br>
    <%= f.text_field :facility_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/businesses/edit.html.erb
<h1>Editing business</h1>

<%= render 'form' %>

<%= link_to 'Show', @business %> |
<%= link_to 'Back', businesses_path %>

app/views/businesses/index.html.erb
<h1>Listing businesses</h1>

<table>
  <thead>
    <tr>
      <th>Dba name</th>
      <th>Aka name</th>
      <th>License</th>
      <th>Facility type</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @businesses.each do |business| %>
      <tr>
        <td><%= business.dba_name %></td>
        <td><%= business.aka_name %></td>
        <td><%= business.license %></td>
        <td><%= business.facility_type %></td>
        <td><%= link_to 'Show', business %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Business', new_business_path %>

app/views/businesses/new.html.erb
<h1>New business</h1>

<%= render 'form' %>

<%= link_to 'Back', businesses_path %>

app/views/businesses/results.html.erb
<% @results.each do |result| %>
	<h1><%= result[0].to_s + " " + result[1].to_s %></h1><br>
	<% result[2].each do |inspection| %>
		<%= inspection[0] %><br>
	<% end %><br><br>
<% end %>

app/views/businesses/search.html.erb
<%= form_tag "/businesses/results", :method => 'post' do %>

  <div class="field">
    <%= label_tag :location %><br>
    <%= text_field_tag :location %>
  </div>
  <div class="actions">
    <%= submit_tag :submit %>
  </div>

<% end %>

app/views/businesses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Dba name:</strong>
  <%= @business.dba_name %>
</p>

<p>
  <strong>Aka name:</strong>
  <%= @business.aka_name %>
</p>

<p>
  <strong>License:</strong>
  <%= @business.license %>
</p>

<p>
  <strong>Facility type:</strong>
  <%= @business.facility_type %>
</p>


<%= link_to 'Back', businesses_path %>