config/routes.rb
ChicagoYelpInspection::Application.routes.draw do
  root "reviews#search"

  resources :inspections
  resources :businesses

  get "/reviews/search" => "reviews#search"
  get "/reviews/results" => "reviews#search"
  post "/reviews/results" => "reviews#results"
  get "/reviews/howto" => "reviews#howto"

end

app/models/inspection.rb
class Inspection < ActiveRecord::Base

	validates :inspect_id, :uniqueness => true
	validates :business_id, :presence => true	

	belongs_to :business
end

app/controllers/inspections_controller.rb
class InspectionsController < ApplicationController
  before_action :set_inspection, only: [:show]

  # GET /inspections
  # GET /inspections.json
  def index
    @inspections = Inspection.all
  end

  # GET /inspections/1
  # GET /inspections/1.json
  def show
    violations = @inspection.violations

    if violations.nil?
      @violations = [["No inspection details on record"]]
    else
      @violations = violations.split("|")
    end
  end

  # GET /inspections/new
  def new
    @inspection = Inspection.new
  end

  # GET /inspections/1/edit
  def edit
  end

  # POST /inspections
  # POST /inspections.json
  def create
    @inspection = Inspection.new(inspection_params)

    respond_to do |format|
      if @inspection.save
        format.html { redirect_to @inspection, notice: 'Inspection was successfully created.' }
        format.json { render action: 'show', status: :created, location: @inspection }
      else
        format.html { render action: 'new' }
        format.json { render json: @inspection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inspections/1
  # PATCH/PUT /inspections/1.json
  def update
    respond_to do |format|
      if @inspection.update(inspection_params)
        format.html { redirect_to @inspection, notice: 'Inspection was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @inspection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inspections/1
  # DELETE /inspections/1.json
  def destroy
    @inspection.destroy
    respond_to do |format|
      format.html { redirect_to inspections_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inspection
      @inspection = Inspection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inspection_params
      params.require(:inspection).permit(:inspect_id, :inspect_date, :results, :violations)
    end
end

app/helpers/inspections_helper.rb
module InspectionsHelper
end

app/views/inspections/_form.html.erb
<%= form_for(@inspection) do |f| %>
  <% if @inspection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inspection.errors.count, "error") %> prohibited this inspection from being saved:</h2>

      <ul>
      <% @inspection.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :inspect_id %><br>
    <%= f.number_field :inspect_id %>
  </div>
  <div class="field">
    <%= f.label :inspect_date %><br>
    <%= f.date_select :inspect_date %>
  </div>
  <div class="field">
    <%= f.label :results %><br>
    <%= f.text_field :results %>
  </div>
  <div class="field">
    <%= f.label :violations %><br>
    <%= f.text_area :violations %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inspections/edit.html.erb
<h1>Editing inspection</h1>

<%= render 'form' %>

<%= link_to 'Show', @inspection %> |
<%= link_to 'Back', inspections_path %>

app/views/inspections/index.html.erb
<h1>Listing inspections</h1>

<table>
  <thead>
    <tr>
      <th>Inspect</th>
      <th>Inspect date</th>
      <th>Results</th>
      <th>Violations</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @inspections.each do |inspection| %>
      <tr>
        <td><%= inspection.inspect_id %></td>
        <td><%= inspection.inspect_date %></td>
        <td><%= inspection.results %></td>
        <td><%= inspection.violations %></td>
        <td><%= link_to 'Show', inspection %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/inspections/new.html.erb
<h1>New inspection</h1>

<%= render 'form' %>

<%= link_to 'Back', inspections_path %>

app/views/inspections/show.html.erb
<p id="notice"><%= notice %></p>

<h3><strong><%= Business.find_by(:id => @inspection.business_id).dba_name %></strong></h3>

<h5?><%= @inspection.inspect_date.to_s + ": " + @inspection.results %></h5><br><br>

<p>
  <strong>Violations</strong><br>
  <% @violations.each do |violation| %>
  	<%= violation %><br><br>
  <% end %>
</p>